project:
  type: book
  output-dir: docs

book:
  title: "The Designometricon"
  author: "Schmettow"
  date: "19/02/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - DMX_1.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

