---
title: "Designometric Rating Scales for Emerging Technologies: Lessons Learned in three projects"
author:
  - name: Martin Schmettow
    id: ut
    orcid: 0000-0003-0240-4087
    email: m.schmettow@utwente.nl
    affiliation: 
      - name: University of Twente
        city: Enschede, NL
        url: www.utwente.nl
    attributes:
        corresponding: true
  - name: Simone Borsci
    id: ut
    orcid: 0000-0002-3591-3577
    email: s.borsci@utwente.nl
    affiliation: 
      - name: University of Twente
        city: Enschede, NL
        url: www.utwente.nl

keywords:
  - Psychometrics
  - User Experience
  - Human Factors
format: docx
#format:
#  elsevier-pdf:
#    keep-tex: true
#    journal:
#      name: PsyRxiv
#      formatting: review
#      #model: 1p # Don't set a model with preprint
#      cite-style: authoryear
bibliography: dmx.bib
date: last-modified
execute:
  echo: false
  warning: false
  message: false
  cache: true

abstract: |
    
---

# Introduction

Use experience rating scales provide cost-effective and readily accessible instruments to evaluate design artifacts, provided they are valid and reliable. [Old wine new bottles] reviewed how UX attributes are commonly measured in the, at the time, emerging field and found rating scales to be a dominant method. However, the review also revealed that the these scales often were ad-hoc, with little to no evidence of validity. 

Here we only address the class of rating scale instruments that actually have been validated, borrowing methods from the field of psychometrics, which is the discipline concerned with accurately measuring attributes of humans, such as their math and language skills, or the individual internal tendencies, such as being open-minded, neurotic or their fear of spiders.

The purpose of *designometric* workflow and analysis is to make sure a UX scale measures attributes of designs correctly. While this appears to be an equivalent problem to psychometric scale development, there is a crucial twist in the transfer: For the evaluation of psychometric instruments, a large sample of participants is required to accurately assess the characteristics of each item, and the contribution it makes to the combined scores for a person (the latent variable).

Evaluation of designometric instruments also is likewise on evaluating item characteristics, but the latent variables are design attributes. Therefore, designometric validation requires extensive design samples to assess the ranking capabilities.
We coined it the *psychometric fallacy*, when an instrument intended to rank designs has been developed without an extensive sample of designs.  While collecting samples may be feasible for classes of designs with a large population, such as university website [Schmettow & Havinga], it generally is more  difficult than a psychometric sample for several reasons, which we will discuss below.

Psychometric tools can easily be re-purposed for designometric analysis, as we will illustrate in this report, but there is structural limitation. 
In psychometrics the basic measurement is an encounter of a person with an item, resulting in a psychometric response matrix. The designometric basic measurement is a three-way encounter of a design, an item and a person, resulting in a three-dimensional data structure, the designometric response box. To make designometric data fit into psychometric tools, the box can be collapsed into a design x item response matrix, hence *flat designometrics*.
We will illustrate the use of psychometric tools in more detail, discuss the limitations of flat designometrics, and propose two directions for deep designometrics.

Generally, rating scale instruments to rank designs are rarely developed with the same standards as psychometric tests [@Bargas-Avila2011]. To our knowledge, only three recent instrument development projects respected the principle of using a large sample of designs to establish designometric scale reliability. In this paper, we summarize our experience in the development of designometric instruments across these three projects.

+ the BUS-11 scale for chatbot evaluation [@Borsci2024]
+ the Consistency & Plausibility scale for VR environments [@Catar2026]
+ UX4CA for the evaluation of conversational agents [@Atzmon2026]

By retracing the development of these three instruments, we report our lessons learned with regard to the following issues:

1. The challenges of collecting design samples for scale development
2. The correct use of psychometric tools for (flat) designometric analysis
3. The role of the psychometric perspective in designometric scale development

# Rating Scales Beyond UX

A main  driver behind the UX revolution was the insight that users are psychologically much deeper than the classic usability framework represents. Usability, as defined in the [ISO 9241-11] depicts the "economic" user, mainly striving for measurable productivity. 
Since psychological concepts tend to become multi-faceted very soon, the UX revolution was accompanied by a proliferation of rating scales, which are supposed to capture the psychological richness of user experience. However, the development of these scales has not followed the same rigorous standards as psychometric instruments, and many of them have not been validated using large samples of designs. This has led to a situation where many UX scales may not be reliable for ranking designs, which is their primary purpose.

As of writing, UX is mainstream, but its dominance may soon decline with the emergence of new design paradigms, such as conversational agents, virtual reality and social robots. These technologies are expected to have a much richer psychological impact on users than traditional interfaces, which means that new designometric instruments will be needed to capture this richness. These domains come with huge, largely unexplored design spaces, for which to navigate effectively, provenly accurate instruments are absolutely necessary. 

In the following sections we will discuss the development of three designometric instruments, that attempt to capture a glimpse of the psychological richness of emerging technology, i.e. conversational agents and virtual reality. 

## BUS-11

## Consistency & Plausibility

The Consistency & Plausibility (CaP) scale was developed to evaluate the design of XR environments. What sets it apart is that the scale design is theory-based, assuming that the degree of immersion in XR environments mainly depends on two cognitive processes, separating the visuo-spatial consistency of the environment and the plausibility of scenario or narrative. The initial item pool of [xx] could therefore be derived from the theory, and was initially divided into two subscales. This theory-derived structure could directly be tested for reliability, needing no separate exploratory step.

The initiative for the development of the CaP came from the naval research institute MARIN, where VR simulators are used for research. An experiment where the same naval scenario was simulated with varying degree of visuo-spatial realism 
under four different conditions with different degrees of visuo-spatial realism was conducted. This allowed to test specifically whether the two subscales were independent.

The second study was conducted to create a design pool large enough to estimate dmx item characteristics. Fortunately, the CaP is intentionally designed to cover XR devices, which encompasses VR simulators, AR systems and even desktop VR, such as many modern gaming titles. This allowed us to obtain a substantial sample of retrospective ratings through a survey on gaming enthusiasts.

The collected measures allowed it to test the theory-derived structure and perform item analysis under both perspectives. The structure were tested per perspective using a Confirmatory Factor Analysis (CFA) model. By using a Bayesian approach, also the variance-covariance parameters could be estimated with precise credibility intervals, which allows to use probabilistic criteria for item selection.

The subscale structure was tested by comparing two-factor models with a one-factor model and prefer the model with the superior predictive power, using the Widely Available Information Criterion (WAIC) [CHECK IC]. The results validated the two-factor structure on the psychometric level. A relatively low correlation between the two subscales confirms the theory of separate cognitive processes. Under the designometric perspective, the one-factor solution prevailed.

Under both perspectives, very good reliability levels could be achieved, with one noteworthy exception: Two of 24 [CHECK] items were intentionally formulated in reverse direction, but after all stood out with such low reliability levels, that they were discarded.


## UX4CA

UX4CA is in development as a UX scale for LLM-driven chatbots. 

+ How was the item pool created?
+ How was the sub-scale structure defined or explored?
+ How was validation by experts performed?
+ How were the design sampled?
+ Use of multi-level models, i.e. deep designometrics.

# Discussion

The main argument of this paper is that designometric instruments must be developed and evaluated using samples of designs, large enough to estimate item characteristics with respect to ranking designs.
In a proper psychometric development process, a large initial item pool is required, as well as one or more large samples of participants to evaluate the item characteristics. Adding a design sample not just adds to the required number of measurements, it starts with defining the design-level target population.

What we can clearly advise against is a very narrow definition, with the worst case that the instrument targets an emerging technology. This is best represented by the BUS-11 project, which focused on the first generation of chatbots, when it had just emerged. Designing a rating scale for emergent technology is very risky for two reasons: First, the population of designs is small and has not yet settled. Second, the fate of algorithmic chatbots demonstrates th Lindy effect: The best estimate for the useful lifetime of a technology is how long it has existed. After years of careful validation  and translation to XX languages, the useful lifetime of the BUS-11 scale is declining with the rapid emerge of LLM-based agents.

The most efficient case in terms of sampling was the CaP study, where the design population was broad and, most importantly, contained designs of everyday use, which allowed for retrospective ratings. Compared to ratings directly after use, retrospective ratings are a spectacular opportunity to validate dmx scales efficiently. 
However, a few caveats apply: 
Most importantly, the subset of everyday use designs must show a strong variation in the measured construct, and must not be too far from the target domain. 
In the CaP case, the moving-platform condition was clearly in a class of its own, but at least two simulator condition would be rated as desktop-level VR. 
A negative example is given in [schmettow2025], which is to evaluate a rating scale for Coolness on a sample of premier law firm homepages.
Next to that, the retrospective rating approach inevitably leads to opportunistic sampling strategies and incomplete data. In the sample of gamers, most participants had experience with only a few titles. 

For latent variable models (CFA, IRM) on sparse data,  is crucial that there are multple observations per participant, and that there is overlap between participants. 
For the same reason, the BUS-11 project developed their design samples incrementally over multiple studies, but *with overlap*.
Building samples incrementally will often be unavoidable in dmx scale development. What should be avoided for specifically is to let disjunct groups of participant rate disjunct sets of designs.

A strong approach to testing specific assumptions about design traits is adding controlled experiments to the workflow, as in the CaP project. Creating a design sample by pure manipulation of design parameters will usually be impossible at scale, but it is useful to observe directly how the designometric signal responds to clearly defined design choices. The experimental results of CaP indicated that the scale is not very sensitive to visual rendering quality, but clearly distinguishes a moving-platform. It is not surprising that adding two new senses (vestibular and proprioceptive) adds considerabl to the experience of a naval boat simulator, but it also shows the limits in discrimating levels of visual fidelity.

Generally, a sampled designs (as opposed to manipulated designs) only carries an instrument to the point where structure and reliability are established, but these are merely internal criteria.
It is not guaranteed that the scale is valid, which means that the scale predicts what the scale user intends to predict.

Proving validity experimentally is the gold standard, but may not always be practical. Using expert ratings is another way to establish validation by external criteria. The UX4CA project used this to validate the scale long before a design sample could be obtained, sufficient for dmx analysis.
Under some restrictions, this is a legit approach, because the predictive value of an instrument is limited by the level of noise. If the predictive value can be demonstrated with external criteria, the actual level of noise becomes secondary. 

While we strongly advocate against an ad-hoc culture of rating scale development as it has happened before [old-wine_new_bottles], using validation early in the process can produce useful preliminary instruments, especially when timeliness matters more than rigor.
After all, design populations tend to emerge, change and perish much faster than human populations, and dedicated instruments are particularly useful in early stages of a design paradigm, when the design space is yet to be fully explored.
As a concrete example, a provisional instrument that approximates emotional reactions to chatbot design can have much more impact than a rigorously validated instrument for measuring usability of commercial websites.
From this perspective, the development of rating scale instruments should rather be seen as a continuous process of revision and improvement, than a one-shot project. Unfortunately, this does not seem to be common practice, maybe because it is not common for psychometric scales. To re-iterate the difference: The human mind has evolved over millions of years, and structurally is not expected to change much in the foreseeable future, while design paradigms can emerge, develop and disappear within a few years.

All three projects also used or analyzed the psychometric perspective at one point or another. The strategy to focus on the psychometric perspective first, as in the BUS-11 project, is not sufficient, but it also is not useless. Items that participants do not use consistently will inevitably add noise to the designometric signal.
Still, early item selection based on psychometric reliability can be a double-edged sword. In the BUS-11 project,  over-reliance on psychometric reliability possibly led to the exclusion of items on the Privacy sub-scale, which in consequence was under-represented. And as we have shown in @schmettow2025, item reliability can dramatically differ between perspectives.

Another question is whether the factor structure of an instrument should be evaluated from the designometric or psychometric perspective. In @schmettow2025 [Figure 3], we have already established that factor structures can differ between perspectives and only occasionally align with the gicen subscale structures of the instrument. This went in both directions: Sometimes the elicited factor structure contains fewer factors than the number of scales implies, sometimes more factors were found than expected.

The CaP project is an interesting case for two reasons: it was strictly derived from cognitive theory and we were able to obtain a complete item response box with just one study, which allowed us to evaluate the factor structure from both perspectives. While the psychometric factor structure was in line with the theoretically structure of the instrument, the designometric factor structure was not.
Technically, this is an example of the Simpson's paradox in factor or regression analysis, but it probably has the following explanation. On the psychometric level, the two factor solution emerged, because the underlying theory was bearing enough truth: The appreciations of consistency and plausibility are independent.

On the designometric level the two factor solution would occur only if there is an analog independence (or separation of concerns) in the design process, implying that efforts and skills in designing for plausibility and consistency are separated. 
While it is easily imaginable that development efforts leading to plausibility (e.g. the physics engine) are separate from developing narratives and scenario design (consistency), in the sample of designs this was simply not the case. 
While one can speculate about potential forces in common design processes, that produce an alignment between the two factors, the bottom line is that factor structures depend strongly on the composition of the samples. One plausible explanation in the case of CaP is that the design sample emerged from a survey on gamers, resulting in a sample of mature and successful designs. 
Perhaps, the two-factor structure would appear in a more curated sample, containing designs in various stages of development.

A rating scale that can serve both perspective, is called a *universal* scale. Two instruments so far fall into this category: The Eeriness scale (Ho & MacDorman) has been shown to be unidimensional and reliable from both perspectives. The CaP scale delivers high reliability for both perspectives, too, but with different factor structures.
The question arises: Should a researcher use the CaP scale for designometric purposes as a uni-dimensional or two-factor scale? Given the early stage of designometrics as a field, as well as limited data, a definite answer cannot yet been given.

The potential of deep designometrics, where both perspectives are regarded simultaneously (i.e. in a single model) has not yet been explored, but two approaches can already be outlined. The first approach is to use multi-level models.
While there are numerous dedicated software packages available for item response models (IRM), some of them can also be formulated as a multi-level common multi-level logistic regression with person and item random effects. While IRMs are designed for psychometric data only, a multi-level model can arbitrarily be extended by adding further ramdom effects levels, including designs, but possibly also tasks or situations. 


Multi-level models were used in the UX4CA project ...

# Conclusion

1. Designometric data is a response box. Nevertheless a variety of psychometric and other statistical tools are available for designometric analysis, either flat or deep.

1. The requirement to test a scale against a large sample of designs is a major challenge for designometric scale development, but strategies exist to make this more efficient, such as using retrospective ratings of everyday use designs, or validating against external criteria.

1. ... 


# AI Statement

During the preparation of this work the authors used ChatGPT exclusively to improve language quality. After using this service, the authors reviewed and edited the content as needed and take full responsibility for the content of the published article.

# References
